# Generated by Django 4.1.7 on 2023-03-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Components",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("component", models.ManyToManyField(to="food.components")),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Quantities",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("measure", models.CharField(max_length=100)),
                ("amount", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Recipes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("servings", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=100)),
                ("ingredients", models.ManyToManyField(to="food.ingredients")),
            ],
        ),
        migrations.CreateModel(
            name="StockProducts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="food.products")),
                ("quantity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="food.quantities")),
            ],
        ),
        migrations.CreateModel(
            name="StockMeals",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=100)),
                ("prepared", models.DateTimeField()),
                ("quantity", models.IntegerField()),
                ("recipe", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="food.recipes")),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(max_length=100)),
                ("recipes", models.ManyToManyField(to="food.recipes")),
            ],
        ),
        migrations.AddField(
            model_name="components",
            name="name",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="food.products"),
        ),
        migrations.AddField(
            model_name="components",
            name="quantity",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="food.quantities"),
        ),
        migrations.AlterUniqueTogether(
            name="components",
            unique_together={("name", "quantity")},
        ),
    ]
