# Generated by Django 4.1.7 on 2023-03-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.IntegerField(choices=[(0, 'Loose'), (1, 'Canned'), (2, 'Dairy'), (3, 'Vegetables'), (4, 'Fruits')]),
        ),
    ]
